# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploiement NODE JS

# Executer quand je push
on: push

# Les tâches
jobs:
  deploy:
    name : Ubuntu
    runs-on : ubuntu-latest

    steps:
      # Pull le git dans le docker temporaire de git
      - name: Pull project
        uses: actions/checkout@v3

      # Install node dans le docker temporaire de git
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # Nettoyer le projet le docker temporaire de git
      - name: Install node module
        run: npm ci

      # Déplacer mon projet dans un serveur
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 161.35.39.34
          username: root
          password: cHocolati31ne
          source: "*"
          target: /home/my_app/

      - name: Run remote script
        uses: appleboy/ssh-action@master
        with:
          host: 161.35.39.34
          username: root
          password: cHocolati31ne
          script: systemctl restart my_app.service
        
